### ISSUE TITLE
Idées pour une meilleure gestion du logiciel libre dans le secteur public

### ISSUE THREAD

**Issue by denismerigoux** [bzg/politique-logiciels-libres-secteur-public#1]
Salut Bastien, merci pour cette initiative. Je réfléchis depuis pas mal de temps à la question de l'informatique dans le secteur public et j'ai quelques idées sur le sujet.

## Premier axe : gestion des ressources humaines

Je pense que la question de l'open source et du logiciel libre est intriquée au mode d'organisation de la production du logiciel dans le secteur public. Tant que les différentes directions et ministère sont silotées, pas de mutualisation possible et donc pas d'intérêt à développer en libre. La DINUM est un premier pas dans cette direction et s'inspire de ce qu'il se fait dans le privé en termes d'organisation agile. Je pense que pour aller plus loin il faut rester dans la logique de la fonction publique.

Concrètement, je proposerais de créer trois nouveaux corps de fonctionnaires. Un corps de catégorie B (pour les techniciens informatique), un corps de catégorie A (pour les programmeurs) et un corps de catégorie A+ (pour le management). Ces corps appartiendraient à la fonction publique d'État et seraient rattachés à un niveau interministériel, à la DINUM par exemple. 

Ainsi, la DINUM permettrait de recenser, regrouper et ventiler les compétences informatiques au sein de l'État vers les différents ministères. Cela permettrait d'éviter le phénomène d'isolement des agents dans une petite DSI qui ne propose pas de perspective d'évolution en terme de carrière ou de progression de compétence.

Deuxième avantage, la DINUM peut offrir à ces corps de fonctionnaires : 
* une formation initiale dans des écoles publiques (universités ou grandes écoles publiques) ;
* une formation continue tout au long de leur carrière afin de se mettre à jour des évolutions techniques.

Je pense que cette solution est celle qui est la plus adaptée aux grands principes qui façonnent le secteur public. En effet, quand l'État identifie un besoin de compétences et un service technique à effectuer, il créé un corps technique de fonctionnaires idoine. C'est ce que l'État a fait pendant des siècles, avant de brusquement s'arrêter après la seconde guerre mondiale, figeant dans l'éternité des corps de fonctionnaires dont l'intitulé n'a plus aucun rapport avec leur fonction initiale (Corps des Mines, Corps des Ponts).

La situation pour l'informatique est d'autant plus critique que le corps des Télécoms, qui remplissait auparavant la fonction de ce corps A+ que je propose, a été tué en 2009 lors de la fusion avec le corps des Mines. Il n'y a donc plus aucun recrutement (sauf 1 ou 2 par an par hasard sur le pool du corps des Mines) de fonctionnaire de catégorie A+ spécialisé en informatique actuellement.

## Deuxième axe : le CNC du logiciel libre

Une deuxième solution que j’avancerai s'inspire elle plus du modèle de financement et de production du logiciel libre et plus largement de la production culturelle indépendante. Je remarque que beaucoup de projets de logiciels libre fondamentaux pour l'infrastructure informatique de beaucoup d'entreprises et d'administrations ne sont maintenus et développés que par une poignée de programmeurs bénévoles qui font ça sur leur temps libre. Le décalage entre l'importance de leur travail et la médiocrité de la reconnaissance qui leur est apporté est abyssal. Cependant, le secteur public, s'il vient à se diriger également vers l'utilisation de projets libres, sera lui aussi dépendant de ces projets de logiciel libre. Il est donc logique que le secteur public contribue à la maintenance de ces projets. Cela peut se faire de trois manières différentes.

Premièrement, détacher des agents du secteur public à la maintenance d'un projet open source. Cela se fait déjà beaucoup dans le privé, lorsque l'entreprise dépend de manière cruciale de la bonne santé d'un projet libre. L'agent détaché est alors une force de travail supplémentaire pour lac maintenance du logiciel, mais cela pose la question de la gouvernance : lorsque trop d'agents payés sont détachés sur un projet libre, ils éclipsent forcément le programmeur original qui fait ça sur son temps libre. Dès lors, cela peut créer des tensions et aboutir à la frustration du programmeur original, se voyant dépossédé par une grosse entité.

Le deuxième mode de contribution est tout simplement d'embaucher le programmeur du logiciel libre. Cela s'apparente à une sorte d'OPA du logiciel par l'entité embaucheuse. Même si c'est efficace et permet de rétribuer le programmeur à sa juste valeur, cela pose aussi des question de gouvernance et de pérennité de la liberté du logiciel dans le futur. En effet, dans ce cas, plus d'incitation à garder le logiciel libre. Bref ce n'est pas vraiment dans l'esprit du libre.

Cette considération me pousse à proposer un mode de contribution différent, inspiré des subventions du CNC. L'État pourrait distribuer des subventions couvrant tout ou partie d'un salaire annuel à des développeurs de logiciel libre portant des projets dont l'État dépend, ou qui sont d'intérêt public ou stratégique. La distribution des subventions pourrait se faire par appel à projet où l'initiative est donnée au secteur du logiciel libre, et la gouvernance pourrait être effectuée par un comité paritaire entre représentants de l'État et représentants de la communauté du logiciel libre (comme le CNC). Cette idée reste à creuser mais elle me plaît car elle permet aux développeurs originaux de garder le contrôle sur leur logiciel, en échange d'un accord contractuel avec l'État qui détaille ce qui est attendu sur le logiciel.

Voilà mes idées sur la question, je suis curieux de savoir ce que tu en penses.

À bientôt,

Denis

**Comment by bzg** [comment]
> Tant que les différentes directions et ministère sont silotées, pas de mutualisation possible et donc pas d'intérêt à développer en libre.

Oui, c'est difficile.  Cela rejoint un constat fait aussi par [Christian Quest](https://medium.com/@cq94/mission-donn%C3%A9es-et-codes-sources-dd684c4b8410), rapporté dans [cette discussion](https://twitter.com/matti_sg_fr/status/1305779800334835714).

Mais avant même d'envisager la mutualisation *active*, l'administration peut publier du code source et rendre possible que ce code serve à d'autres, notamment quand il s'agit de petits modules.

Par exemple, une recherche sur ["etalab" dans les dépendances](https://code.etalab.gouv.fr/fr/deps?q=etalab) sort des modules `npm` qui ne sont pas des « communs » mais qui servent (beaucoup?) à d'autres, dans le privé et le public.

> Concrètement, je proposerais de créer trois nouveaux corps de fonctionnaires.

Tu vois loin !  Pareil, je trouve l'idée intéressante, mais que peut-on faire *pour l'instant* ?  Je crois que nous devons commencer par comprendre les besoins actuels de formation des milliers d'informaticiens du secteur public, et voir de quelle façon les enjeux associés au logiciel libre peuvent s'intégrer à un renouvellement des offres de formation.  Mais tu notes que cette proposition n'est pas en contradiction avec la tienne :)

> ... figeant dans l'éternité des corps de fonctionnaires dont l'intitulé n'a plus aucun rapport avec leur fonction initiale (Corps des Mines, Corps des Ponts).

... d'où ma proposition ci-dessus, car je doute que l'éternité s'achève bientôt.

> Il n'y a donc plus aucun recrutement (sauf 1 ou 2 par an par hasard sur le pool du corps des Mines) de fonctionnaire de catégorie A+ spécialisé en informatique actuellement.

Ouch.  Je n'avais pas identifié ce problème - c'en est un, effectivement !

> Je remarque que beaucoup de projets de logiciels libre fondamentaux pour l'infrastructure informatique de beaucoup d'entreprises et d'administrations ne sont maintenus et développés que par une poignée de programmeurs bénévoles qui font ça sur leur temps libre.  Le décalage entre l'importance de leur travail et la médiocrité de la reconnaissance qui leur est apporté est abyssal.

Oui, je fais le même constat.

> Premièrement, détacher des agents du secteur public à la maintenance d'un projet open source.

Oui.  Une idée similaire a longtemps été proposée du côté de l'éducation : les enseignants qui ont construit [www.sesamath.net](https://www.sesamath.net) sur leur temps libre n'ont jamais obtenu de décharge, sauf quelques rares exceptions.

> Le deuxième mode de contribution est tout simplement d'embaucher le programmeur du logiciel libre.

Je crois beaucoup à cette piste, l'administration y gagnerait beaucoup sur plusieurs plan : celui de l'efficacité (en recrutant la bonne personne), de l'indépendance (en évitant d'avoir recours à un tiers) et de l'attractivité (en faisant un recrutement ayant des chances d'en attirer d'autres.

> Cette idée reste à creuser mais elle me plaît car elle permet aux développeurs originaux de garder le contrôle sur leur logiciel, en échange d'un accord contractuel avec l'État qui détaille ce qui est attendu sur le logiciel.

Oui, je trouve cela très astucieux et cela vient préciser une proposition générale que je faisais dans [cet entretien](https://bzg.fr/le-logiciel-libre-a-besoin-d-une-vraie-strategie-de-mutualisation-au-sein-de-letat.html/) quand j'évoque l'idée d'une fondation pour le financement de projet libres du secteur public.

Je vois comment intégrer toutes tes idées dans le README.md et je te ping dans cette issue.

Merci encore pour ce partage !

**Comment by denismerigoux** [comment]
> > Concrètement, je proposerais de créer trois nouveaux corps de fonctionnaires.
> 
> Tu vois loin ! Pareil, je trouve l'idée intéressante, mais que peut-on faire _pour l'instant_ ? Je crois que nous devons commencer par comprendre les besoins actuels de formation des milliers d'informaticiens du secteur public, et voir de quelle façon les enjeux associés au logiciel libre peuvent s'intégrer à un renouvellement des offres de formation. Mais tu notes que cette proposition n'est pas en contradiction avec la tienne :)

Oui je sais bien que je vais loin avec cette idée, mais je pense que se fixer des caps permet de mieux penser les actions à court terme. En ce qui concerne la formation actuelle des informaticiens du secteur public, j'ai surtout l'impression que les agents recrutés sur concours manquent cruellement d'une formation universitaire basique à l'informatique. À la DGFiP, j'ai vu des équipes entières de programmeurs avec personne qui n'avait l'équivalent d'une licence en informatique. Évidemment, cela est largement du à la faible attractivité des rémunérations du secteur public par rapport au privé. Même si cela va être difficile à régler, une première mesure pourrait être le pré-recrutement des agents sur concours dès la L1 ou L2 à la manière des professeurs. Le fait d'avoir des études payées pourrait compenser les salaires plus faibles pour beaucoup de gens surtout issus de classes défavorisées, mais qui ont eu la chance d'accéder à l'université. 

> ... d'où ma proposition ci-dessus, car je doute que l'éternité s'achève bientôt.

L'avenir sera ce que nous en ferons non? ;)

> Ouch. Je n'avais pas identifié ce problème - c'en est un, effectivement !

C'est un énorme problème complètement passé sous silence, et qui montre une profonde méconnaissance du secteur informatique par l'ensemble de la haute administration.

> Je vois comment intégrer toutes tes idées dans le README.md et je te ping dans cette issue.
> 
> Merci encore pour ce partage !

De rien :)

**Comment by bzg** [comment]
Je me suis permis de tenter de condenser cela dans les propositions 43 et 44 - je réouvre pour poursuivre la discussion.

**Comment by bzg** [comment]
> Oui je sais bien que je vais loin avec cette idée, mais je pense que se fixer des caps permet de mieux penser les actions à court terme.

Oui, tout à fait d'accord - et l'esprit des temps semble remettre les Grands Plans à la mode, donc il est permis de rester optimiste.

> Même si cela va être difficile à régler, une première mesure pourrait être le pré-recrutement des agents sur concours dès la L1 ou L2 à la manière des professeurs. 

Oui, mais le tout nouveau CAPES d'informatique peine déjà à attirer les foules...

En tous cas merci, j'espère que le résumé des propositions te va.

**Comment by denismerigoux** [comment]
Autres remarques sur ce que j'ai pu apercevoir lors de mes pérégrinations dans l'administration : 
* la plupart des managers ne reviewent pas le code produit par leurs agents, donc pour ça la proposition de la plateforme de review de "code moche" est excellente
* évidemment les méthodes agiles ne sont utilisées presque nulle part, mais lorsque certains managers veulent les utiliser, ils n'ont aucun contrôle sur les agents qu'on leur donne pour réaliser leur tâche et c'est difficile d'utiliser des méthodes agiles avec des gens qui n'y ont jamais été formé -> plus de formation continue pour les agents ?
* aucune communication entre la recherche publique appliquée et l'administration, pourquoi pas permettre aux universités et instituts de recherche de détacher des chercheurs appliqués dans l'administration pour expérimenter une innovation ? En effet, j'ai acquis la conviction pendant mon doctorat que la vraie innovation ne peut se faire que par la combinaison d'une organisation adaptée (petites équipes, liberté d'action) et de personnes ayant les compétences nécessaires à réaliser cette innovation.

**Comment by GeoffNN** [comment]
Merci @bzg pour l'initiative, et @denismerigoux pour avoir enfin posté tes réflexions. Je reviendrai plus tard pour un commentaire plus long, mais un premier point important: **Pourquoi distinguer hiérarchiquement les personnels techniques et de management ?** Il me semble que de tels postes / corps auraient une force de frappe bien supérieur s'ils contenaient deux "tracks" au même niveau: l'un technique, et l'autre managerial. C'est ce que font à peu près toutes les boîtes de tech outre-Atlantique. Ca permet d'éviter aux techniciens excellents de devenir de mauvais managers par obligation de promotion.

Si l'ambition est de _faire_ à nouveau dans l'Etat, au lieu de _faire faire_, il semble important qu'il y ait un statut A+ technique.

**Comment by bzg** [comment]
Merci pour ces commentaires - j'ai ajouté les idées 45 et 46.
