### ISSUE TITLE
Idées en vrac : conversion de fichiers

### ISSUE THREAD

**Issue by revolunet** [bzg/politique-logiciels-libres-secteur-public#3]
Proposer une API de conversion ODT, DOCX, PDF.... utilisable pas diverses applications pour faciliter l'adoption des formats libres sans que chaque projet ait besoin d'implémenter/maintenir son propre service

**Comment by bzg** [comment]
Par exemple [cette issue](https://github.com/SocialGouv/code-du-travail-numerique/issues/2712) :-) ?

Sinon je vois à peu près l'idée mais comment tu verrais l'implémentation: un utilisateur envoie une requête (`POST`?) à cette API avec les données à convertir et reçoit le fichier converti en réponse ?

**Comment by revolunet** [comment]
dans le mile :) j'ai vu le sujet popper sur le slack beta/dev aujourd'hui aussi

Oui une API "stateless" en POST avec un token d'auth

**Comment by bzg** [comment]
J'ai ajouté l'idée qui est l'idée 42, ça devrait te porter chance :)
